-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 15:14:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tblMensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblMensajes` (
  `IdMensaje` INT NOT NULL,
  `Asunto` TEXT NULL DEFAULT NULL,
  `DestinatarioGlobal` TEXT NULL DEFAULT NULL,
  `FechaEnvio` DATETIME NULL DEFAULT NULL,
  `Mensaje` TEXT NULL DEFAULT NULL,
  `TipoMensaje` TEXT NULL DEFAULT NULL,
  `Remitente` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IdMensaje`));


-- -----------------------------------------------------
-- Table `tblResultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblResultados` (
  `IdResultado` INT NOT NULL COMMENT 'Identificador de la anomalia',
  `IdTipoOrdenTrabajo` INT NOT NULL COMMENT 'Identificador del tipo de orden de trabajo.',
  `IdEstadoMedida` INT NOT NULL COMMENT 'Identificador del estado de la medida.',
  `IdTipoActividad` INT NOT NULL COMMENT 'Identificador del tipo de actividad asociado.',
  `Codigo` NVARCHAR(10) NOT NULL COMMENT 'Codigo de anomalia',
  `Descripcion` NVARCHAR(100) NOT NULL COMMENT 'Descripcion de la anomalia',
  PRIMARY KEY (`IdResultado`))
ENGINE = InnoDB
COMMENT = 'Lista que contiene los resultados posibles para cada tipo de' /* comment truncated */ /* orden de trabajo, el campo IdResultado se maneja de forma interna y no se repite.*/;


-- -----------------------------------------------------
-- Table `sisSeguimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisSeguimientos` (
  `IdSeguimiento` INT NOT NULL,
  `Altitud` REAL NULL DEFAULT NULL,
  `Exactitud` INT NULL DEFAULT NULL,
  `FechaHoraSeguimiento` DATETIME NULL DEFAULT NULL,
  `Latitud` REAL NULL DEFAULT NULL,
  `Longitud` REAL NULL DEFAULT NULL,
  `Serial` TEXT NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdSeguimiento`));


-- -----------------------------------------------------
-- Table `tblMensajesOut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblMensajesOut` (
  `IdMensajeOut` INT NOT NULL,
  `Asunto` TEXT NULL DEFAULT NULL,
  `FechaEnvio` DATETIME NULL DEFAULT NULL,
  `Texto` TEXT NULL DEFAULT NULL,
  `Tipo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IdMensajeOut`));


-- -----------------------------------------------------
-- Table `sisUsuariosRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisUsuariosRol` (
  `idUsuarioRol` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuarioRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisFuncionesRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisFuncionesRol` (
  `idFuncion` INT NOT NULL,
  `Funcion` VARCHAR(255) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncion`, `Rol`),
  INDEX `fk_sisFuncionesRol_sisUsuariosRol1_idx` (`Rol` ASC),
  CONSTRAINT `fk_sisFuncionesRol_sisUsuariosRol1`
    FOREIGN KEY (`Rol`)
    REFERENCES `sisUsuariosRol` (`Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tblResultadoAcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblResultadoAcciones` (
  `IdResultadoAcciones` BIGINT NOT NULL COMMENT 'identificador del grupo a que las acciones pertenecen',
  `IdResultado` INT NOT NULL COMMENT 'codigo de la anomalia, no se puede usar aca el valor 0 este se usa  para las observaciones que no tienen una anomalia asociada',
  `IdAccion` INT NOT NULL COMMENT 'identificador de la accion a  realizar para la anomalia seleccionada',
  `Valor` NVARCHAR(200) NOT NULL,
  PRIMARY KEY (`IdResultadoAcciones`),
  UNIQUE INDEX `IdAnomalia_UNIQUE` (`IdResultado` ASC),
  UNIQUE INDEX `IdAccion_UNIQUE` (`IdAccion` ASC),
  CONSTRAINT `fk_tblAnomaliaAccion_tblAnomalia1`
    FOREIGN KEY (`IdResultado`)
    REFERENCES `tblResultados` (`IdResultado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'listado de acciones a realizar para el resultado seleccionad' /* comment truncated */ /*a*/;


-- -----------------------------------------------------
-- Table `tblOrdenesDeTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblOrdenesDeTrabajo` (
  `IdOrden` BIGINT NOT NULL,
  `NumeroOrden` NVARCHAR(15) NOT NULL,
  `IdEvento` BIGINT NULL DEFAULT NULL,
  `IdTipoDeOrden` SMALLINT NOT NULL,
  `IdSuscriptor` NVARCHAR(15) NOT NULL,
  `Prioridad` NVARCHAR(10) NULL DEFAULT NULL,
  `FechaSolicitud` DATETIME NOT NULL,
  `FechaVisitar` DATETIME NULL DEFAULT NULL,
  `Ruta` NVARCHAR(16) NOT NULL,
  `NombreTitular` NVARCHAR(70) NOT NULL,
  `Direccion` NVARCHAR(170) NOT NULL,
  `Localizacion` NVARCHAR(100) NOT NULL,
  `Municipio` NVARCHAR(80) NOT NULL,
  `Telefono` NVARCHAR(30) NULL DEFAULT NULL,
  `Secuencia` SMALLINT NOT NULL,
  `Objetivo` NVARCHAR(300) NOT NULL,
  `Observacion` NVARCHAR(500) NULL DEFAULT NULL,
  `Longitud` DECIMAL(20,17) NOT NULL,
  `Latitud` DECIMAL(20,17) NOT NULL,
  `IdEstado` SMALLINT NOT NULL DEFAULT 0,
  `FechaVencimiento` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`));


-- -----------------------------------------------------
-- Table `tblOrdenesDeTrabajoCampos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblOrdenesDeTrabajoCampos` (
  `IdOrden` BIGINT NOT NULL,
  `Campo` NVARCHAR(20) NOT NULL,
  `Valor` NVARCHAR(1000) NULL DEFAULT NULL,
  `Grupo` NVARCHAR(20) NOT NULL,
  `Orden` VARCHAR(45) NULL,
  `TipoDato` NVARCHAR(20) NOT NULL,
  `Visible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdOrden`, `Campo`, `TipoDato`),
  CONSTRAINT `fk_tblOrdenesDeTrabajoCampos_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblListaDetalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblListaDetalles` (
  `IdListaDetalle` BIGINT NOT NULL AUTO_INCREMENT,
  `IdLista` INT NOT NULL,
  `Valor` NVARCHAR(50) NOT NULL,
  `Descripcion` NVARCHAR(255) NULL DEFAULT NULL,
  `Reservado1` NVARCHAR(255) NULL DEFAULT NULL,
  `Reservado2` NVARCHAR(255) NULL DEFAULT NULL,
  `Reservado3` NVARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IdListaDetalle`),
  UNIQUE INDEX (`Valor` ASC));


-- -----------------------------------------------------
-- Table `tblRotAccionesTomadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAccionesTomadas` (
  `IdOrden` BIGINT NOT NULL,
  `CodigoAccion` NVARCHAR(50) NOT NULL,
  `ContenidoEscritoAccion` NVARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `CodigoAccion`),
  CONSTRAINT `fk_tblRotAccionesTomadas_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotAcometidaEncontrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAcometidaEncontrada` (
  `IdOrden` BIGINT NOT NULL,
  `TipoInstalacion` NVARCHAR(12) NULL DEFAULT NULL,
  `Estado` NVARCHAR(10) NULL DEFAULT NULL,
  `Ubicacion` NVARCHAR(30) NULL DEFAULT NULL,
  `Calibre` NVARCHAR(4) NULL DEFAULT NULL,
  `Material` NVARCHAR(10) NULL DEFAULT NULL,
  `Longitud` NVARCHAR(5) NULL DEFAULT NULL,
  `RedDistribucion` NVARCHAR(10) NULL DEFAULT NULL,
  `Concentrico` TINYINT(1) NULL DEFAULT NULL,
  `TipoAcometida` NVARCHAR(7) NULL DEFAULT NULL,
  `Diametro` NVARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotAcometidaEncontrada_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotAcometidaInstalada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAcometidaInstalada` (
  `IdOrden` BIGINT NOT NULL,
  `TipoInstalacion` NVARCHAR(12) NULL DEFAULT NULL,
  `Ubicaccion` NVARCHAR(30) NULL DEFAULT NULL,
  `Calibre` NVARCHAR(4) NULL DEFAULT NULL,
  `Material` NVARCHAR(10) NULL DEFAULT NULL,
  `Longitud` NVARCHAR(5) NULL DEFAULT NULL,
  `RedDistribucion` NVARCHAR(10) NULL DEFAULT NULL,
  `Concentrico` TINYINT(1) NULL DEFAULT NULL,
  `TipoAcometida` NVARCHAR(7) NULL DEFAULT NULL,
  `Diametro` NVARCHAR(4) NULL DEFAULT NULL,
  `Propiedad` NVARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotAcometidaInstalada_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotActa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotActa` (
  `IdOrden` BIGINT NOT NULL,
  `FormatoActa` VARCHAR(6) NOT NULL,
  `SerieActa` VARCHAR(16) NOT NULL,
  `Descripcion` VARCHAR(30) NOT NULL,
  `SeImprimio` TINYINT(1) NULL DEFAULT NULL,
  `SeFirmo` TINYINT(1) NULL DEFAULT NULL,
  `TipoActa` NVARCHAR(10) NULL DEFAULT NULL,
  `UsuarioPresente` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `FormatoActa`, `SerieActa`),
  CONSTRAINT `fk_tblRotActa_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotAforo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAforo` (
  `IdOrden` BIGINT NOT NULL,
  `CodigoAparato` DECIMAL(18,0) NOT NULL,
  `CantidadAparatos` INT NOT NULL,
  `TipoCarga` VARCHAR(12) NOT NULL,
  `TipoServicio` VARCHAR(15) NOT NULL,
  `ClaseServicio` VARCHAR(12) NOT NULL,
  `PotenciaTotal` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`IdOrden`, `CodigoAparato`),
  CONSTRAINT `fk_tblRotAforo_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotAforoComplemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAforoComplemento` (
  `IdOrden` BIGINT NOT NULL,
  `TieneEstufa` TINYINT(1) NULL DEFAULT NULL,
  `TieneCilindro` TINYINT(1) NULL DEFAULT NULL,
  `TieneCalentador` TINYINT(1) NULL DEFAULT NULL,
  `TotalCargaM` DECIMAL(12,2) NULL DEFAULT NULL,
  `TotalCargaDirecta` DECIMAL(12,2) NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotAforoComplemento_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotAnomalia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAnomalia` (
  `IdOrden` BIGINT NOT NULL,
  `CodigoAnomalia` VARCHAR(6) NOT NULL,
  `TipoAnomalia` NVARCHAR(5) NOT NULL,
  `Observaciones` NVARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `CodigoAnomalia`, `TipoAnomalia`),
  CONSTRAINT `fk_tblRotAnomalia_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotCustodia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotCustodia` (
  `IdOrden` BIGINT NOT NULL,
  `IdMaterial` VARCHAR(36) NOT NULL,
  `Formato` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`IdOrden`, `IdMaterial`, `Formato`),
  CONSTRAINT `fk_tblRotCustodia_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotEquipoEncontrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotEquipoEncontrado` (
  `IdOrden` BIGINT NOT NULL,
  `IdEquipo` VARCHAR(15) NOT NULL,
  `CodigoMarcaEquipo` VARCHAR(6) NOT NULL,
  `CodigoModeloEquipo` VARCHAR(6) NULL,
  `CodigoTipoEquipo` VARCHAR(6) NOT NULL,
  `AnoFabricacion` SMALLINT NULL,
  `Tension` VARCHAR(6) NULL,
  `Corriente` NVARCHAR(6) NULL DEFAULT NULL,
  `UnConstante` VARCHAR(3) NULL DEFAULT NULL,
  `Constante` VARCHAR(3) NULL DEFAULT NULL,
  `FactorMult` VARCHAR(10) NULL DEFAULT NULL,
  `Fase` NVARCHAR(6) NULL DEFAULT NULL,
  `LecturaAct` NVARCHAR(20) NULL DEFAULT NULL,
  `LecturaFpAct` NVARCHAR(20) NULL DEFAULT NULL,
  `LecturaReact` NVARCHAR(20) BINARY NULL DEFAULT NULL,
  `LecturaFpReact` NVARCHAR(20) NULL DEFAULT NULL,
  `FecRel` INT NULL DEFAULT NULL,
  `CorPrimCT` NVARCHAR(6) NULL DEFAULT NULL,
  `CorSecCT` NVARCHAR(6) NULL DEFAULT NULL,
  `PotPrimPT` NVARCHAR(6) NULL DEFAULT NULL,
  `PotSecPT` NVARCHAR(6) NULL DEFAULT NULL,
  `CertificadoCalibracion` NVARCHAR(20) NULL DEFAULT NULL,
  `EstadoMedidor` NVARCHAR(20) NULL DEFAULT NULL,
  `Ubicacion` NVARCHAR(20) NULL DEFAULT NULL,
  `Diametro` NVARCHAR(20) NULL DEFAULT NULL,
  `HayMedidaCentralizada` TINYINT(1) NULL DEFAULT NULL,
  `SeRetiro` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`IdOrden`, `IdEquipo`, `CodigoMarcaEquipo`, `CodigoTipoEquipo`),
  CONSTRAINT `fk_tblRotEquipoEncontrado_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotEquipoInstalado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotEquipoInstalado` (
  `IdOrden` BIGINT NOT NULL,
  `IdEquipo` VARCHAR(15) NOT NULL,
  `CodigoMarcaEquipo` VARCHAR(6) NOT NULL,
  `CodigoModeloEquipo` VARCHAR(6) NULL,
  `CodigoTipoEquipo` VARCHAR(6) NOT NULL,
  `AnoFabricacion` SMALLINT NULL,
  `Tension` VARCHAR(6) NULL,
  `Corriente` NVARCHAR(6) NULL DEFAULT NULL,
  `UnConstante` VARCHAR(3) NULL DEFAULT NULL,
  `Constante` VARCHAR(3) NULL DEFAULT NULL,
  `FactorMult` VARCHAR(10) NULL DEFAULT NULL,
  `Fase` NVARCHAR(6) NULL DEFAULT NULL,
  `LecturaAct` NVARCHAR(20) NULL DEFAULT NULL,
  `LecturaFpAct` NVARCHAR(20) NULL DEFAULT NULL,
  `LecturaReact` NVARCHAR(20) BINARY NULL DEFAULT NULL,
  `LecturaFpReact` NVARCHAR(20) NULL DEFAULT NULL,
  `FecRel` INT NULL DEFAULT NULL,
  `CorPrimCT` NVARCHAR(6) NULL DEFAULT NULL,
  `CorSecCT` NVARCHAR(6) NULL DEFAULT NULL,
  `PotPrimPT` NVARCHAR(6) NULL DEFAULT NULL,
  `PotSecPT` NVARCHAR(6) NULL DEFAULT NULL,
  `CertificadoCalibracion` NVARCHAR(20) NULL DEFAULT NULL,
  `Ubicacion` NVARCHAR(20) NULL DEFAULT NULL,
  `Diametro` NVARCHAR(20) NULL DEFAULT NULL,
  `HayMedidaCentralizada` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `IdEquipo`, `CodigoMarcaEquipo`, `CodigoTipoEquipo`),
  CONSTRAINT `fk_tblRotEquipoInstalado_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotInspeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotInspeccion` (
  `IdOrden` BIGINT NOT NULL,
  `NombreAtendio` VARCHAR(40) NULL,
  `CodigoCalidadAtiende` VARCHAR(6) NULL,
  `CodigoTipoDocumento` VARCHAR(6) NULL,
  `NumeroDocumento` VARCHAR(16) NULL,
  `CodigoLugarExpedicion` VARCHAR(10) NULL,
  `Telefono` VARCHAR(14) NULL DEFAULT NULL,
  `CodigoCiiu` VARCHAR(40) NULL DEFAULT NULL,
  `CodigoTensionServicio` VARCHAR(6) NULL DEFAULT NULL,
  `Observacion` VARCHAR(500) NULL DEFAULT NULL,
  `CodigoTransformador` VARCHAR(16) NULL,
  `UbicacionDireccion` VARCHAR(1) NULL,
  `Direccion` VARCHAR(170) NULL,
  `Localizacion` VARCHAR(100) NULL DEFAULT NULL,
  `PotenciaPuntoTransformacion` DECIMAL(22,3) NULL DEFAULT 0,
  `PuntoTransformacionExclusivo` TINYINT(1) NULL DEFAULT 0,
  `CodigoComercializadora` INT NULL DEFAULT 0,
  `CodigoZona` VARCHAR(3) NULL,
  `CodigoMunicipio` VARCHAR(8) NULL,
  `VeredaBarrio` VARCHAR(50) NULL,
  `PuntoFisico` DECIMAL(10,0) NULL,
  `Carga` DECIMAL(18,8) NULL DEFAULT NULL,
  `ClaseServicio` NVARCHAR(20) NULL DEFAULT NULL,
  `Asesoria` TINYINT(1) NULL DEFAULT NULL,
  `Celular` NVARCHAR(20) NULL DEFAULT NULL,
  `Email` NVARCHAR(50) NULL DEFAULT NULL,
  `ObservacionAnomalia` NVARCHAR(500) NULL DEFAULT NULL,
  `NodoTrafo` NVARCHAR(16) NULL DEFAULT NULL,
  `NivelTension` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `FormatoActa` NVARCHAR(6) NULL DEFAULT NULL,
  `CodigoResultadoImp` INT NULL DEFAULT NULL,
  `SERegistrado` NVARCHAR(10) NULL DEFAULT NULL,
  `AreaPredio` DECIMAL(7,2) NULL DEFAULT NULL,
  `AreaResidencial` INT NULL DEFAULT NULL,
  `AreaNoResidencial` INT NULL DEFAULT NULL,
  `NumeroFamilias` NVARCHAR(2) NULL DEFAULT NULL,
  `NumeroHabitantes` NVARCHAR(2) NULL DEFAULT NULL,
  `TipoUsoCorresponde` NVARCHAR(3) NULL DEFAULT NULL,
  `UsoRealResidencial` NVARCHAR(15) NULL DEFAULT NULL,
  `NombreTestigo` NVARCHAR(40) NULL DEFAULT NULL,
  `TipoDocTestigo` NVARCHAR(6) NULL DEFAULT NULL,
  `NumeroDocTestigo` NVARCHAR(16) NULL DEFAULT NULL,
  `LugarExpDocTestigo` NVARCHAR(10) NULL DEFAULT NULL,
  `Comercializadora` VARCHAR(150) NULL DEFAULT NULL,
  `NT` TINYINT UNSIGNED NULL DEFAULT NULL,
  `FechaInicioVisita` VARCHAR(30) NULL DEFAULT NULL,
  `FechaFinVisita` VARCHAR(30) NULL DEFAULT NULL,
  `LongitudSitio` DECIMAL(20,17) NULL DEFAULT NULL,
  `LatitudSitio` DECIMAL(20,17) NULL DEFAULT NULL,
  `AlturaSitio` DECIMAL(8,4) NULL DEFAULT NULL,
  `ProveedorCoordenada` NVARCHAR(50) NULL DEFAULT NULL,
  `PrecisionCoordenada` DECIMAL(20,17) NULL DEFAULT NULL,
  `UsuarioEjecutor` NVARCHAR(50) NULL DEFAULT NULL,
  `ElUsuarioFirmo` TINYINT(1) NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotInspeccion_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotMaterialNoSeriado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotMaterialNoSeriado` (
  `IdOrden` BIGINT NOT NULL,
  `CodigoMaterial` INT NOT NULL,
  `Retirado` TINYINT(1) NOT NULL DEFAULT 0,
  `TipoMaterial` INT NOT NULL,
  `CantidadUtilizada` DECIMAL(10,2) NOT NULL,
  `ValorMaterialUtilizado` DECIMAL(11,0) NOT NULL,
  `UnidadDeMedida` NVARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `CodigoMaterial`, `Retirado`),
  CONSTRAINT `fk_tblRotMaterialNoSeriado_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotNuevaConexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotNuevaConexion` (
  `IdOrden` BIGINT NOT NULL,
  `PuntoTransf` NVARCHAR(15) NOT NULL,
  `LatitudTransf` DECIMAL(18,0) NULL DEFAULT NULL,
  `LongitudTransf` DECIMAL(18,0) NULL DEFAULT NULL,
  `AlturaTransf` DECIMAL(18,0) NULL DEFAULT NULL,
  `CodNodoTransf` NVARCHAR(10) NULL DEFAULT NULL,
  `PuntoUsuario` NVARCHAR(15) NULL DEFAULT NULL,
  `LatitudUsuario` DECIMAL(18,0) NULL DEFAULT NULL,
  `LongitudUsuario` DECIMAL(18,0) NULL DEFAULT NULL,
  `AlturaUsuario` DECIMAL(18,0) NULL DEFAULT NULL,
  `CodNodoUsuario` NVARCHAR(10) NULL DEFAULT NULL,
  `NivelTensionUsuario` INT NULL DEFAULT NULL,
  `NumOrden` NVARCHAR(37) NULL DEFAULT NULL,
  `TipoPredio` NVARCHAR(20) NULL DEFAULT NULL,
  `Area` NVARCHAR(10) NULL DEFAULT NULL,
  `TipoUso` NVARCHAR(5) NULL DEFAULT NULL,
  `Estrato` NVARCHAR(2) NULL DEFAULT NULL,
  `NumRuta` NVARCHAR(100) NULL DEFAULT NULL,
  `NumCiclo` NVARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `PuntoTransf`),
  CONSTRAINT `fk_tblRotNuevaConexion_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotObra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotObra` (
  `IdOrden` BIGINT NOT NULL,
  `RedTrenzada` TINYINT(1) NOT NULL,
  `PuntoConsumoNormalizado` TINYINT(1) NOT NULL,
  `UbicacionCaja` SMALLINT NOT NULL,
  `ExteriorizacionCaja` TINYINT(1) NOT NULL,
  `NumeroMedidoresMonofasicos` DECIMAL(5,0) NOT NULL,
  `NumeroMedidoresBifasicos` DECIMAL(5,0) NOT NULL,
  `NumeroMedidoresTrifasicos` DECIMAL(5,0) NOT NULL,
  `TipoAcometida` DECIMAL(5,0) NOT NULL,
  `CalibreCable` DECIMAL(5,0) NOT NULL,
  `LongitudCable` INT NOT NULL,
  `TipoRed` DECIMAL(5,0) NOT NULL,
  `SolicitudCable` DECIMAL(5,0) NOT NULL,
  `DiametroDucto` INT NOT NULL,
  `LongitudDucto` INT NOT NULL,
  `TipoDucto` DECIMAL(5,0) NOT NULL,
  `SolicitudDucto` DECIMAL(5,0) NOT NULL,
  `EstadoCaja` DECIMAL(5,0) NOT NULL,
  `TipoCaja` DECIMAL(5,0) NOT NULL,
  `SolicitudCaja` DECIMAL(5,0) NOT NULL,
  `EstadoInterruptor` DECIMAL(5,0) NOT NULL,
  `UbicacionTermofundente` DECIMAL(5,0) NOT NULL,
  `UbicacionPinCorte` DECIMAL(5,0) NOT NULL,
  `ExistenciaBarraje` DECIMAL(5,0) NOT NULL,
  `SolicitudInterruptor` DECIMAL(5,0) NOT NULL,
  `EstadoPoloTierra` DECIMAL(5,0) NOT NULL,
  `TipoVarilla` VARCHAR(25) NOT NULL,
  `CalibreVarilla` VARCHAR(25) NOT NULL,
  `SolicitudPoloTierra` DECIMAL(5,0) NOT NULL,
  `EstadoPilar` DECIMAL(5,0) NOT NULL,
  `ObservacionPilar` VARCHAR(25) NOT NULL,
  `SolicitudPilar` DECIMAL(5,0) NOT NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotObra_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotPagare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotPagare` (
  `IdOrden` BIGINT NOT NULL,
  `ValorTotal` DOUBLE NULL DEFAULT NULL,
  `Cuotas` INT NULL DEFAULT NULL,
  `ValorCuota` DOUBLE NULL DEFAULT NULL,
  `NombreDeudor` NVARCHAR(40) NULL DEFAULT NULL,
  `NumeroDocumentoDeudor` NVARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotPagare_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotPrueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotPrueba` (
  `IdOrden` BIGINT NOT NULL,
  `TipoPrueba` NVARCHAR(10) NOT NULL,
  `TipoPatron` NVARCHAR(10) NULL DEFAULT NULL,
  `NumeroPatron` NVARCHAR(30) NULL DEFAULT NULL,
  `ValorConstante` DECIMAL(18,0) NULL DEFAULT NULL,
  `UnidadConstante` NVARCHAR(4) NULL DEFAULT NULL,
  `CorrienteCalibracionBajaCarga` DECIMAL(18,0) NULL DEFAULT NULL,
  `Tension` DECIMAL(18,0) NULL DEFAULT NULL,
  `TiempoMin` INT NULL DEFAULT NULL,
  `TiempoSeg` DECIMAL(6,3) NULL DEFAULT NULL,
  `NumeroGiros` INT NULL DEFAULT NULL,
  `PorcErrorEC` DECIMAL(18,0) NULL DEFAULT NULL,
  `ConformeCalibracionBajaCarga` TINYINT(1) NULL DEFAULT NULL,
  `LecturaInicial` DECIMAL(18,0) NULL DEFAULT NULL,
  `LecturaFinal` DECIMAL(18,0) NULL DEFAULT NULL,
  `CorrienteCalibracionAlta` DECIMAL(18,0) NULL DEFAULT NULL,
  `TensionCalibracionAlta` DECIMAL(18,0) NULL DEFAULT NULL,
  `TiempoMinCalibracionAlta` INT NULL DEFAULT NULL,
  `TiempoSegCalibracionAlta` INT NULL DEFAULT NULL,
  `PorcErrorEP` DECIMAL(18,0) NULL DEFAULT NULL,
  `ConformeCalibracionAlta` TINYINT(1) NULL DEFAULT NULL,
  `ConformePruebaSinCarga` TINYINT(1) NULL DEFAULT NULL,
  `PorcErrorTotal` DECIMAL(18,0) NULL DEFAULT NULL,
  `ConformeTotal` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `TipoPrueba`),
  CONSTRAINT `fk_tblRotPrueba_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotSelloInstalado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotSelloInstalado` (
  `IdOrden` BIGINT NOT NULL,
  `IdMaterial` VARCHAR(36) NOT NULL,
  `CodigoColor` VARCHAR(6) NOT NULL,
  `CodigoMaterial` VARCHAR(6) NOT NULL,
  `UbicacionSello` VARCHAR(6) NOT NULL,
  `TipoComponente` NVARCHAR(6) NULL DEFAULT NULL,
  `IdComponente` NVARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `IdMaterial`),
  CONSTRAINT `fk_tblRotSelloInstalado_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotSelloEncontrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotSelloEncontrado` (
  `IdOrden` BIGINT NOT NULL,
  `IdSello` INT NOT NULL,
  `CodigoMarca` VARCHAR(6) NULL,
  `CodigoModelo` VARCHAR(6) NULL,
  `CodigoColor` VARCHAR(6) NOT NULL,
  `CodigoMaterial` VARCHAR(6) NOT NULL,
  `UbicacionSello` VARCHAR(6) NOT NULL,
  `Retirado` TINYINT(1) NOT NULL,
  `CondicionSello` VARCHAR(50) NOT NULL,
  `TipoComponente` NVARCHAR(6) NULL DEFAULT NULL,
  `IdComponente` NVARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`, `IdSello`),
  CONSTRAINT `fk_tblRotSelloRetirado_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotSobre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotSobre` (
  `IdOrden` BIGINT NOT NULL,
  `IdMaterial` VARCHAR(36) NOT NULL,
  `Formato` VARCHAR(6) NOT NULL,
  `CantidadSellos` INT NOT NULL,
  PRIMARY KEY (`IdOrden`, `IdMaterial`, `Formato`),
  CONSTRAINT `fk_tblRotSobre_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblMateriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblMateriales` (
  `IdMaterial` BIGINT NOT NULL AUTO_INCREMENT,
  `Tipo` NVARCHAR(16) NOT NULL,
  `Numero` NVARCHAR(10) NOT NULL,
  `CodigoModelo` NVARCHAR(10) NOT NULL,
  `CodigoMarca` NVARCHAR(10) NOT NULL,
  `IdOrden` BIGINT NULL,
  `IdEstado` TINYINT(1) NOT NULL DEFAULT 0,
  `CodigoColor` VARCHAR(45) NULL,
  `Observacion` VARCHAR(45) NULL,
  `CodigoTipo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tblMaterialesNoSeriados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblMaterialesNoSeriados` (
  `IdMaterialNS` BIGINT NOT NULL AUTO_INCREMENT,
  `CodigoImpresion` BIGINT NULL,
  `CodigoMaterial` NVARCHAR(30) NOT NULL,
  `Descripcion` NVARCHAR(255) NULL,
  `IdTipoMaterial` BIGINT NOT NULL,
  `TipoGestion` BIGINT NULL DEFAULT 0,
  `UnidadMedida` NVARCHAR(255) NULL,
  `ValorUnitario` BIGINT NULL,
  PRIMARY KEY (`IdMaterialNS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tblRotPruebaAgua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotPruebaAgua` (
  `IdOrden` BIGINT NOT NULL,
  `TipoPrueba` VARCHAR(10) NOT NULL,
  `FugasPerceptibles` TINYINT(1) NULL,
  `LocalizacionFugasPerceptibles` VARCHAR(100) NULL,
  `RegistraConLlavesCerradas` TINYINT(1) NULL,
  `FugasImperceptibles` TINYINT(1) NULL,
  `LocalizacionFugasImperceptibles` VARCHAR(100) NULL,
  `Aforo` VARCHAR(5) NULL,
  `CuentaContratoCruce1` INT NULL,
  `DireccionCruce1` VARCHAR(170) NULL,
  `TipoCruce1` VARCHAR(20) NULL,
  `MarcaMedidorCruce1` INT NULL,
  `NumeroSerieCruce1` INT NULL,
  `LecturaCruce1` DECIMAL NULL,
  `CuentaContratoCruce2` INT NULL,
  `DireccionCruce2` VARCHAR(170) NULL,
  `TipoCruce2` VARCHAR(20) NULL,
  `MarcaMedidorCruce2` INT NULL,
  `NumeroSerieCruce2` INT NULL,
  `LecturaCruce2` DECIMAL NULL,
  PRIMARY KEY (`IdOrden`, `TipoPrueba`),
  CONSTRAINT `fk_table1_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tblRotAforoAguaComplemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAforoAguaComplemento` (
  `IdOrden` BIGINT NOT NULL,
  `TieneTanqueAlmacenamiento` TINYINT(1) NULL DEFAULT NULL,
  `TieneReboseCisternas` TINYINT(1) NULL DEFAULT NULL,
  `TieneReboseEnTanques` TINYINT(1) NULL DEFAULT NULL,
  `TieneEvidenciaDeReparacion` TINYINT(1) NULL DEFAULT NULL,
  `ReparacionDonde` NVARCHAR(500) NULL,
  `PuntosHidraulicos` INT NULL,
  `TanquesBajos` INT NULL,
  `TanquesAltos` INT NULL,
  `CapacidadTanquesBajos` INT NULL,
  `CapacidadTanquesAltos` INT NULL,
  `EstadoDeTanques` VARCHAR(5) NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotAforoAguaComplemento_tblOrdenesDeTrabajo1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tblRotAcometidaEncontradaAgua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAcometidaEncontradaAgua` (
  `IdOrden` BIGINT NOT NULL,
  `Estado` NVARCHAR(10) NULL DEFAULT NULL,
  `Material` NVARCHAR(10) NULL DEFAULT NULL,
  `Diametro` NVARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotAcometidaEncontrada_tblOrdenesDeTrabajo10`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tblRotAcometidaInstaladaAgua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblRotAcometidaInstaladaAgua` (
  `IdOrden` BIGINT NOT NULL,
  `Material` NVARCHAR(10) NULL DEFAULT NULL,
  `Diametro` NVARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrden`),
  CONSTRAINT `fk_tblRotAcometidaEncontrada_tblOrdenesDeTrabajo100`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `tblOrdenesDeTrabajo` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
