/**
 * Copyright 2016 Wireless&Mobile, Inc. All rights reserved
 * Generated by the generator tool for the AMF Generator.
 */

package ${packageNameMain};

import java.math.BigDecimal;
import java.util.Date;

public class ${className} {


<#list properties as property>
    private ${property["Tipo"]} ${property["Atributo"]?uncap_first};
</#list>
    /**
     * Constructor without parameter.
     * 
     */
    public ${className}() {
        super();
    }
    
    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ${className}(<#list properties as property> ${property["Tipo"]} ${property["Atributo"]?uncap_first}<#if property_has_next>, </#if></#list>) {
        this();
<#list properties as property>
        this.${property["Atributo"]?uncap_first} = ${property["Atributo"]?uncap_first};
</#list>
    }
    
<#list properties as property>
   /**
    * Returns the value of the "${property["Atributo"]?uncap_first}" attribute.
    *
    * @return The value of the "${property["Atributo"]?uncap_first}" attribute.
    */
   public ${property["Tipo"]} get${property["Atributo"]?cap_first}() {
      return ${property["Atributo"]?uncap_first};
   }
   
    /**
    * Sets the value of the "${property["Atributo"]?uncap_first}" attribute.
    *
    * @param ${property["Atributo"]?uncap_first}
    *     The value of the "${property["Atributo"]?uncap_first}" attribute.
    */
   public void set${property["Atributo"]?cap_first}(${property["Tipo"]} ${property["Atributo"]?uncap_first}) {
      this.${property["Atributo"]?uncap_first} = ${property["Atributo"]?uncap_first};
   }
</#list>
}